// shared/config.js - Cross-environment config

export const CONFIG = {
  // Server scheduling
  CHECKS_PER_MEETING: 2,
  ARM_DELAY_SEC: 30,
  FIRST_CHECK_WINDOW_MIN: [2, 8],
  NEXT_CHECK_WINDOW_MIN: [8, 20],
  RESPONSE_DEADLINE_SEC: 30,
  
  // Verification rules
  SCHEDULED_CHALLENGE_COUNT: 2,
  ONDEMAND_CHALLENGE_COUNT: 3,
  CHALLENGE_TIME_MS: 15000,
  JOIN_CHECK_ENABLED: true,
  GUEST_POLICY: 'attention',
  LOG_DETAIL: 'with_reason',
  DEMO_FAST_SCHEDULE: false,

  // AI & Liveness Thresholds
  YAW_TARGET_DEG: 28,
  YAW_TRIGGER_DEG: 20,
  YAW_HOLD_MS: 250,
  BIG_TURN_DEG: 40,
  PITCH_UP_DEG: 12,

  EAR_CLOSE_RATIO: 0.70,
  EAR_OPEN_RATIO: 0.85,
  BLINK_MIN_MS: 60,
  BLINK_MAX_MS: 400,

  MAR_OPEN: 0.55,
  MAR_HOLD_MS: 500,
  HAND_MOUTH_HOLD_MS: 300,
  
  GAZE_SHIFT_RATIO: 0.18,
  GAZE_HOLD_MS: 400,
  GAZE_MAX_HEAD_YAW: 12,

  // Blendshape simplifications
  BLENDSHAPE_SMILE: 0.4,
  BLENDSHAPE_JAW_OPEN: 0.45,
  BLENDSHAPE_BLINK: 0.45,
  BLENDSHAPE_BROW_UP: 0.4,
  BLENDSHAPE_PUCKER: 0.5,

  // Identity
  IDENTITY_MATCH_DISTANCE: 0.50,
  MIN_IDENTITY_CHECKS: 3,
  FRONTAL_YAW_MAX_FOR_ID: 15,
  FACE_LOSS_GRACE_MS: 500,
  OCCLUSION_GRACE_MS: 1200,
  MIN_DEPTH_RANGE: 0.03,
  ENROLL_SAMPLES: 5
};
